# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
email: jacobsiddall@gmail.com
title: Cadence
meta_description: Studio and One-bedroom apartments for rent in and Nashville Tennessee
keywords: Apartment for Rent in Nashville Tennessee, studio apartments, one-bedroom apartments, West End Apartments in Nashville
baseurl: "/cadence" # the subpath of your site, e.g. /blog
url: "http://tbd.com" # the base hostname & protocol for your site
twitter_username: jjsiddall
github_username:  jjsiddall

# Build settings
markdown: kramdown
